### ISSUE TITLE
[部分修复]无序列表下有序列表的编号问题

### ISSUE THREAD

**Issue by ChengzuHuang** [yuuuxt/siyuan-gitbook-azure#14]
如图：之前有个一级的有序列表，排到了 3，于是之后所有二级的有序列表全部变成了 3 开头。
![image](https://user-images.githubusercontent.com/10935766/108585910-0e708880-7386-11eb-991d-d59634ddb564.png)

**Comment by yuuuxt** [comment]
这个问题无法完全解决, 0.1.0中对附图的情况作了处理, 再往下嵌套还是有问题的. 

谢谢@ihyw

**Comment by yuuuxt** [comment]
目前1.2 (alpha) 版已修正了此问题, 不再需要在主题中特别处理了
