### ISSUE TITLE
建议：各级无序列表的小圆点全部统一

### ISSUE THREAD

**Issue by ChengzuHuang** [yuuuxt/siyuan-gitbook-azure#15]
利用竖线连线已经能很好地展示层级了。这种实心圆->空心圆->方块的意义不大，反而干扰了视线，而且也不美观。
![image](https://user-images.githubusercontent.com/10935766/108586060-0ebd5380-7387-11eb-91c6-9b317659e028.png)

**Comment by yuuuxt** [comment]
同意, 晚些时候改下
