### ISSUE TITLE
代办事项渲染有错误

### ISSUE THREAD

**Issue by SysFlat** [yuuuxt/siyuan-gitbook-azure#21]
![image](https://user-images.githubusercontent.com/19515782/114692492-3effed80-9d4b-11eb-8212-dba388ba28ff.png)

**Comment by yuuuxt** [comment]
可以提供一段示例markdown吗?

**Comment by SysFlat** [comment]
之前出现问题的是win7 64位平台，换了win10之后问题不存在了。。。

**Comment by yuuuxt** [comment]
好的, closing for now :)
