### ISSUE TITLE
mac下 待办事项 渲染错误

### ISSUE THREAD

**Issue by Re-TinyLin** [yuuuxt/siyuan-gitbook-azure#22]
环境：
- macOS big sur 11.3.1 
- 思源  v1.1.83 

错误代码：
`- [ ] todo item1`
渲染结果：
![image](https://user-images.githubusercontent.com/75683978/118771503-34d68f00-b8b5-11eb-98df-ee280e017b18.png)

期望效果：(默认daylight主题下的）
![image](https://user-images.githubusercontent.com/75683978/118771553-43bd4180-b8b5-11eb-9040-5addec615139.png)

关闭的issue中有类似的情况 https://github.com/yuuuxt/siyuan-gitbook-azure/issues/21
但是我在win10的台式机上也是渲染错误。

以及，感谢您的主题样式！

**Comment by Re-TinyLin** [comment]
Update:
定位到问题了，您在custom.css中定义了这个样式。
```
/* 列表 */
.vditor ul > li{
    list-style-type: circle;
}
```

而原先默认待办事项的样式如下：
```
.vditor-task {
    list-style: none;
    word-break: break-all;
}
```
css对应的属性被覆盖了，导致其list-style又出现了。。。


自行fix了，在custom.css加入了相应的规则。

```
/* 代办事项前不需要原来默认的list-style */
.vditor .vditor-task{
    list-style: none;
}
```

再次感谢您！

**Comment by yuuuxt** [comment]
感谢! 晚上我修一下发个新版本 :)

**Comment by yuuuxt** [comment]
因本机已安装了1.2 alpha版, 直接使用了你提供的fix更新了一版. 感谢!
