### ISSUE TITLE
有序列表换行问题

### ISSUE THREAD

**Issue by aobatu** [yuuuxt/siyuan-gitbook-azure#9]
参考如下图片：
![image](https://user-images.githubusercontent.com/24941288/106442700-8dc11980-64b6-11eb-9b24-54d4fae35a5e.png)

**Comment by yuuuxt** [comment]
目前的最新版已经修复了, 更新到最新版看看? 
https://github.com/siyuan-note/bazaar/pull/48

**Comment by aobatu** [comment]
做了如下操作后，问题依旧，还是没有恢复。
1、更新软件到“当前版本 v0.7.5”；
2、恢复外观到默认样式；（默认样式下展示无问题）
3、在社区集市中卸载此样式；
4、然后重新应用样式，仍旧出现换行问题。

**Comment by yuuuxt** [comment]
我这测试了一下是正常的; 有一个方便区分的方法, 当前样式是"1.1.", "1.2.1." 这样的, 目前的最新版是"1.1", "1.2.1"这样的, 没有最后的".", 如还有, 说明当前主题版本还不是最新版

**Comment by aobatu** [comment]
果然是旧版本原因。我如下操作后，问题解决了：
1、先换成默认的，然后重置视图；
2、关闭笔记；
3、重新打开，再应用样式就好了。

**Comment by aobatu** [comment]
@yuuuxt  顺便讲一下，这个样式是我目前看到最好的！换个N个都没有这个适合我。非常感谢能分享出来！
